RSS_SOURCES = [
    {
        "name": "TechCrunch",
        "feed_url": "https://techcrunch.com/feed/",
        "url": "https://techcrunch.com",
        "category": "tech",
        "country": "US",
        "language": "en",
        "enabled": True,
        "trust_level": "medium",
    },
    {
        "name": "Ars Technica",
        "feed_url": "https://feeds.arstechnica.com/arstechnica/index",
        "url": "https://arstechnica.com",
        "category": "tech",
        "country": "US",
        "language": "en",
        "enabled": True,
        "trust_level": "medium",
    },
    {
        "name": "Wired",
        "feed_url": "https://www.wired.com/feed/rss",
        "url": "https://www.wired.com",
        "category": "tech",
        "country": "US",
        "language": "en",
        "enabled": True,
        "trust_level": "medium",
    },
    {
        "name": "Hacker News",
        "feed_url": "https://news.ycombinator.com/rss",
        "url": "https://news.ycombinator.com",
        "category": "tech",
        "country": "US",
        "language": "en",
        "enabled": True,
        "trust_level": "medium",
    },
    {
        "name": "BBC World",
        "feed_url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "url": "https://www.bbc.com/news/world",
        "category": "world",
        "country": "GB",
        "language": "en",
        "enabled": True,
        "trust_level": "high",
    },
    {
        "name": "The Guardian World",
        "feed_url": "https://www.theguardian.com/world/rss",
        "url": "https://www.theguardian.com/world",
        "category": "world",
        "country": "GB",
        "language": "en",
        "enabled": True,
        "trust_level": "high",
    },
    {
        "name": "Al Jazeera",
        "feed_url": "https://www.aljazeera.com/xml/rss/all.xml",
        "url": "https://www.aljazeera.com",
        "category": "world",
        "country": "GLOBAL",
        "language": "en",
        "enabled": True,
        "trust_level": "medium",
    },
    {
        "name": "DW English",
        "feed_url": "https://rss.dw.com/rdf/rss-en-all",
        "url": "https://www.dw.com/en",
        "category": "world",
        "country": "DE",
        "language": "en",
        "enabled": True,
        "trust_level": "medium",
    },
]
